defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m
  parallelism: 1

version: 2
jobs:
  "Make Dependencies":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Init Gradle
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: ~/code
          paths:
            - ./*
  "Unit Tests":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
  "Lint":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
  "KtLint":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Run Kotlin Linter
          command: ./gradlew ktlint
      - store_artifacts:
          path: app/build/reports
          destination: reports
  "DeteKt":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Run DeteKt
          command: ./gradlew detekt
      - store_artifacts:
          path: app/build/reports
          destination: reports
  "Decode Keystore":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code/keystore
      - run:
          name: Decode
          command: echo $KEYSTORE | base64 --decode > ~/code/keystore/Keystore.jks
      - persist_to_workspace:
          root: ~/code
          paths:
            - keystore/*
  "Import Fabric Properties":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code/app
      - run:
          name: Import Properties
          command: echo -e "apiSecret=${FABRIC_API_SECRET}\napiKey=${FABRIC_API_KEY}" >> ~/code/app/fabric.properties
      - persist_to_workspace:
          root: ~/code
          paths:
            - app/fabric.properties
  "Build App":
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks
      - persist_to_workspace:
          root: ~/code
          paths:
            - ./*
  "Deploy Fabric":
    <<: *defaults
    working_directory: ~/code
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - deploy:
          name: Deploy Fabric
          command: ./gradlew crashlyticsUploadDistributionRelease
  "Deploy AppCenter":
    <<: *defaults
    working_directory: ~/code
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - deploy:
          name: Deploy AppCenter
          command: ./gradlew -Pdeploy=true deployAppCenter -i
workflows:
  version: 2
  build:
    jobs:
      - "Make Dependencies"
      - "Decode Keystore"
      - "Import Fabric Properties":
          filters:
            branches:
              only: master
      - "Lint":
          requires:
            - "Make Dependencies"
      - "KtLint":
          requires:
            - "Make Dependencies"
      - "DeteKt":
          requires:
            - "Make Dependencies"
      - "Unit Tests":
          requires:
            - "Make Dependencies"
      - "Build App":
          requires:
            - "Make Dependencies"
            - "Lint"
            - "KtLint"
            - "DeteKt"
            - "Unit Tests"
            - "Decode Keystore"
      - "Deploy Hold":
          type: approval
          requires:
            - "Build App"
      - "Deploy Fabric":
          requires:
            - "Build App"
            - "Import Fabric Properties"
            - "Deploy Hold"
          filters:
            branches:
              only: master
      - "Deploy AppCenter":
          requires:
            - "Build App"
            - "Deploy Hold"